class CalendarService {
    getData() {
        return Object.values(options);
    }
}

var options = {
    'language': {
        'ar': 'ARABIC',
        'eu': 'BASQUE',
        'bg': 'BULGARIAN',
        'bn': 'BENGALI',
        'ca': 'CATALAN',
        'cs': 'CZECH',
        'da': 'DANISH',
        'de': 'GERMAN',
        'el': 'GREEK',
        'en': 'ENGLISH',
        'en-AU': 'ENGLISH (AUSTRALIAN)',
        'en-GB': 'ENGLISH (GREAT BRITAIN)',
        'es': 'SPANISH',
        'eu': 'BASQUE',
        'fa': 'FARSI',
        'fi': 'FINNISH',
        'fil': 'FILIPINO',
        'fr': 'FRENCH',
        'gl': 'GALICIAN',
        'gu': 'GUJARATI',
        'hi': 'HINDI',
        'hr': 'CROATIAN',
        'hu': 'HUNGARIAN',
        'id': 'INDONESIAN',
        'it': 'ITALIAN',
        'iw': 'HEBREW',
        'ja': 'JAPANESE',
        'kn': 'KANNADA',
        'ko': 'KOREAN',
        'lt': 'LITHUANIAN',
        'lv': 'LATVIAN',
        'ml': 'MALAYALAM',
        'mr': 'MARATHI',
        'nl': 'DUTCH',
        'nn': 'NORWEGIAN NYNORSK',
        'no': 'NORWEGIAN',
        'or': 'ORIYA',
        'pl': 'POLISH',
        'pt': 'PORTUGUESE',
        'pt-BR': 'PORTUGUESE (BRAZIL)',
        'pt-PT': 'PORTUGUESE (PORTUGAL)',
        'rm': 'ROMANSCH',
        'ro': 'ROMANIAN',
        'ru': 'RUSSIAN',
        'sk': 'SLOVAK',
        'sl': 'SLOVENIAN',
        'sr': 'SERBIAN',
        'sv': 'SWEDISH',
        'tl': 'TAGALOG',
        'ta': 'TAMIL',
        'te': 'TELUGU',
        'th': 'THAI',
        'tr': 'TURKISH',
        'uk': 'UKRAINIAN',
        'vi': 'VIETNAMESE',
        'zh-CN': 'CHINESE (SIMPLIFIED)',
        'zh-TW': 'CHINESE (TRADITIONAL)'
    },
    'region': {
        'ac': 'Ascensão',
        'ad': 'Andorra',
        'ae': 'Emirados Árabes Unidos',
        'af': 'Afeganistão',
        'ag': 'Antígua e Barbuda',
        'ai': 'Anguilla',
        'al': 'Albânia',
        'am': 'Arménia',
        'an': 'Antilhas Holandesas',
        'ao': 'Angola',
        'aq': 'Antártida',
        'ar': 'Argentina',
        'as': 'Samoa Americana',
        'at': 'Áustria',
        'au': 'Austrália',
        'aw': 'Aruba',
        'az': 'Azerbaijão',
        'ba': 'Bósnia e Herzegovina',
        'bb': 'Barbados',
        'bd': 'Bangladesh',
        'be': 'Bélgica',
        'bf': 'Burkina Faso',
        'bg': 'Bulgária',
        'bh': 'Bahrein',
        'bi': 'Burundi',
        'bj': 'Benim',
        'bm': 'Bermudas',
        'bn': 'Brunei Darussalam',
        'bo': 'Bolívia',
        'br': 'Brasil',
        'bs': 'Bahamas',
        'bt': 'Butão',
        'bv': 'Ilha Bouvet',
        'bw': 'Botswana',
        'by': 'Bielorrússia',
        'bz': 'Belize',
        'ca': 'Canadá',
        'cc': 'Ilhas Cocos',
        'cd': 'República Democrática do Congo',
        'cf': 'República Centro-Africana',
        'cg': 'República do Congo',
        'ch': 'Suíça',
        'ci': 'Costa do Marfim',
        'ck': 'Ilhas Cook',
        'cl': 'Chile',
        'cm': 'Camarões',
        'cn': 'República Popular da China',
        'co': 'Colômbia',
        'cr': 'Costa Rica',
        'cu': 'Cuba',
        'cv': 'Cabo Verde',
        'cx': 'Ilha Natal',
        'cy': 'Chipre',
        'cz': 'República Tcheca',
        'de': 'Alemanha (Deutschland)',
        'dj': 'Djibouti',
        'dk': 'Dinamarca',
        'dm': 'Dominica',
        'do': 'República Dominicana',
        'dz': 'Argélia',
        'ec': 'Equador',
        'ee': 'Estónia',
        'eg': 'Egipto',
        'er': 'Eritreia',
        'es': 'Espanha',
        'et': 'Etiópia',
        'eu': 'Europa',
        'fi': 'Finlândia',
        'fj': 'Fiji',
        'fk': 'Malvinas (Falkland Islands)',
        'fm': 'Estados Federados da Micronésia',
        'fo': 'Ilhas Feroé',
        'fr': 'França',
        'ga': 'Gabão',
        'uk': 'Reino Unido',
        'gd': 'Granada',
        'ge': 'Geórgia',
        'gf': 'Guiana Francesa',
        'gg': 'Guernsey',
        'gh': 'Gana',
        'gi': 'Gibraltar',
        'gl': 'Gronelândia',
        'gm': 'Gâmbia',
        'gn': 'Guiné',
        'gp': 'Guadalupe',
        'gq': 'Guiné Equatorial',
        'gr': 'Grécia',
        'gs': 'Ilhas Geórgia do Sul e Sandwich do Sul',
        'gt': 'Guatemala',
        'gu': 'Guam',
        'gw': 'Guiné-Bissau',
        'gy': 'Guiana',
        'hk': 'Hong Kong',
        'hm': 'Ilha Heard e Ilhas McDonald',
        'hn': 'Honduras',
        'hr': 'Croácia',
        'ht': 'Haiti',
        'hu': 'Hungria',
        'id': 'Indonésia',
        'ie': 'Irlanda',
        'il': 'Israel',
        'im': 'Ilha de Man',
        'in': 'Índia',
        'io': 'Território Britânico do Oceano Índico',
        'iq': 'Iraque',
        'ir': 'Irão',
        'is': 'Islândia',
        'it': 'Itália',
        'je': 'Jersey',
        'jm': 'Jamaica',
        'jo': 'Jordânia',
        'jp': 'Japão',
        'ke': 'Quénia',
        'kg': 'Quirguistão',
        'kh': 'Camboja',
        'ki': 'Kiribati',
        'km': 'Comores',
        'kn': 'Saint Kitts e Nevis',
        'kr': 'Coreia do Sul',
        'kw': 'Kuwait',
        'ky': 'Ilhas Caiman',
        'kz': 'Cazaquistão',
        'la': 'Laos',
        'lb': 'Líbano',
        'lc': 'Santa Lúcia',
        'li': 'Liechtenstein',
        'lk': 'Sri Lanka',
        'lr': 'Libéria',
        'ls': 'Lesoto',
        'lt': 'Lituânia',
        'lu': 'Luxemburgo',
        'lv': 'Letónia',
        'ly': 'Líbia',
        'ma': 'Marrocos',
        'mc': 'Mónaco',
        'md': 'Moldávia',
        'me': 'Montenegro',
        'mg': 'Madagáscar',
        'mh': 'Ilhas Marshall',
        'mk': 'Antiga República Jugoslava da Macedónia',
        'ml': 'Mali',
        'mm': 'Myanmar',
        'mn': 'Mongólia',
        'mo': 'Macau',
        'mp': 'Marianas Setentrionais',
        'mq': 'Martinica',
        'mr': 'Mauritânia',
        'ms': 'Montserrat',
        'mt': 'Malta',
        'mu': 'Maurício',
        'mv': 'Maldivas',
        'mw': 'Malawi',
        'mx': 'México',
        'my': 'Malásia',
        'mz': 'Moçambique',
        'nb': 'Namíbia',
        'nc': 'Nova Caledónia',
        'ne': 'Níger',
        'nf': 'Ilha Norfolk',
        'ng': 'Nigéria',
        'ni': 'Nicarágua',
        'nl': 'Países Baixos',
        'no': 'Noruega',
        'np': 'Nepal',
        'nr': 'Nauru',
        'nu': 'Niue',
        'nz': 'Nova Zelândia',
        'om': 'Omã',
        'pa': 'Panamá',
        'pe': 'Peru',
        'pf': 'Polinésia Francesa',
        'pg': 'Papua-Nova Guiné',
        'ph': 'Filipinas',
        'pk': 'Paquistão',
        'pl': 'Polónia',
        'pm': 'Saint-Pierre e Miquelon',
        'pn': 'Ilhas Pitcairn',
        'pr': 'Porto Rico',
        'ps': 'Territórios palestinianos (i.e., Cisjordânia e Faixa de Gaza)',
        'pt': 'Portugal',
        'pw': 'Palau',
        'py': 'Paraguai',
        'qa': 'Qatar',
        're': 'Reunião (ilha)',
        'ro': 'Roménia',
        'ru': 'Rússia',
        'rw': 'Ruanda',
        'sa': 'Arábia Saudita',
        'sb': 'Ilhas Salomão',
        'sc': 'Seychelles',
        'sd': 'Sudão',
        'se': 'Suécia',
        'sg': 'Singapura',
        'sh': 'Santa Helena (território)',
        'si': 'Eslovénia',
        'sj': 'Ilhas Svalbard e Jan Mayen',
        'sk': 'Eslováquia',
        'sl': 'Serra Leoa',
        'sm': 'San Marino',
        'sn': 'Senegal',
        'so': 'Somália',
        'sr': 'Suriname',
        'ss': 'Sudão do Sul',
        'st': 'São Tomé e Príncipe',
        'sv': 'El Salvador',
        'sy': 'Síria',
        'sz': 'Suazilândia',
        'tc': 'Ilhas Turcas e Caicos',
        'td': 'Chade',
        'tf': 'Terras Austrais e Antárticas Francesas',
        'tg': 'Togo',
        'th': 'Tailândia',
        'tj': 'Tajiquistão',
        'tk': 'Tokelau',
        'tl': 'Timor-Leste',
        'tm': 'Turquemenistão',
        'tn': 'Tunísia',
        'to': 'Tonga',
        'tr': 'Turquia',
        'tt': 'Trinidad e Tobago',
        'tv': 'Tuvalu',
        'tw': 'Taiwan',
        'tz': 'Tanzânia',
        'ua': 'Ucrânia',
        'ug': 'Uganda',
        'uk': 'Reino Unido',
        'um': 'Ilhas Menores Distantes dos Estados Unidos',
        'us': 'selected="selected">Estados Unidos',
        'uy': 'Uruguai',
        'uz': 'Uzbequistão',
        'va': 'Vaticano',
        'vc': 'São Vicente e Granadinas',
        've': 'Venezuela',
        'vg': 'Ilhas Virgens Britânicas',
        'vi': 'Ilhas Virgens Americanas',
        'vn': 'Vietname',
        'vu': 'Vanuatu',
        'wf': 'Wallis e Futuna',
        'ws': 'Samoa (antes, Samoa Ocidental)',
        'ye': 'Iémen',
        'yt': 'Mayotte',
        'yu': 'Jugoslávia',
        'za': 'África do Sul',
        'zm': 'Zâmbia',
        'zw': 'Zimbabwe'
    },
    'maptype': {
        0: 'roadmap',
        1: 'satellite',
        2: 'hybrid',
        3: 'terrain'
    },
    'format': {
        'png': 'PNG (8-bit)',
        'png32': 'PNG (32-bit)',
        'gif': 'GIF',
        'jpg': 'JPEG',
        'jpg-baseline': 'non-progressive JPEG'
    }
}