class FilterService {
	getData() {
		return options;
	}
}

var options = {
	location: {
		label: 'Location Parameters',
		data: [
			{
				name: 'center',
				label: 'Center',
				placeholder: 'Berkeley, CA'
			},
			{
				name: 'zoom',
				label: 'Zoom',
				data: [1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 , 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
			}
		]
	},
	map: {
		label: 'Map Parameters',
		data: [
			{
				name: 'size',
				label: 'Size',
				placeholder: '400x400'
			},
			{
				name: 'scale',
				label: 'Scale',
				data: [
					{ name: 'one', label: 'one' },
					{ name: 'one', label: 'one' }
				]
			},
			{
				name: 'format',
				label: 'Format',
				data: [
					{label: 'gif', name: 'GIF'},
					{label: 'jpg', name: 'JPEG'},
					{label: 'png', name: 'PNG (8-bit)'},
					{label: 'png32', name: 'PNG (32-bit)'},
					{label: 'jpg-baseline', name: 'non-progressive JPEG'}
				]
			},
			{
				name: 'maptype',
				label: 'Maptype',
				data: [
					{label: 'hybrid', name: 'Hybrid'},
					{label: 'roadmap', name: 'Road Map'},
					{label: 'terrain', name: 'Terrain'},
					{label: 'satellite', name: 'Satellite'}
				]
			},
			{
				name: 'language',
				label: 'Language',
				data: language
			},
			{
				name: 'region',
				label: 'Region',
				data: region
			}
		]
	},
	feature: {
		label: 'Feature Parameters',
		data: [
			{
				name: 'markers',
				label: 'Markers'
			},
			{
				name: 'path',
				label: 'Path'
			},
			{
				name: 'visible',
				label: 'Visible'
			},
			{
				name: 'style',
				label: 'Style'
			}
		]
	},
	reporting: {
		label: 'Reporting Parameters',
		data: [
			{
				name: 'sensor',
				label: 'Sensor',
				data: ['true', 'false']
			}
		]
	}
};

var region = [
	{label: 'ac', name: 'Ascensão'},
	{label: 'ad', name: 'Andorra'},
	{label: 'ae', name: 'Emirados Árabes Unidos'},
	{label: 'af', name: 'Afeganistão'},
	{label: 'ag', name: 'Antígua e Barbuda'},
	{label: 'ai', name: 'Anguilla'},
	{label: 'al', name: 'Albânia'},
	{label: 'am', name: 'Arménia'},
	{label: 'an', name: 'Antilhas Holandesas'},
	{label: 'ao', name: 'Angola'},
	{label: 'aq', name: 'Antártida'},
	{label: 'ar', name: 'Argentina'},
	{label: 'as', name: 'Samoa Americana'},
	{label: 'at', name: 'Áustria'},
	{label: 'au', name: 'Austrália'},
	{label: 'aw', name: 'Aruba'},
	{label: 'az', name: 'Azerbaijão'},
	{label: 'ba', name: 'Bósnia e Herzegovina'},
	{label: 'bb', name: 'Barbados'},
	{label: 'bd', name: 'Bangladesh'},
	{label: 'be', name: 'Bélgica'},
	{label: 'bf', name: 'Burkina Faso'},
	{label: 'bg', name: 'Bulgária'},
	{label: 'bh', name: 'Bahrein'},
	{label: 'bi', name: 'Burundi'},
	{label: 'bj', name: 'Benim'},
	{label: 'bm', name: 'Bermudas'},
	{label: 'bn', name: 'Brunei Darussalam'},
	{label: 'bo', name: 'Bolívia'},
	{label: 'br', name: 'Brasil'},
	{label: 'bs', name: 'Bahamas'},
	{label: 'bt', name: 'Butão'},
	{label: 'bv', name: 'Ilha Bouvet'},
	{label: 'bw', name: 'Botswana'},
	{label: 'by', name: 'Bielorrússia'},
	{label: 'bz', name: 'Belize'},
	{label: 'ca', name: 'Canadá'},
	{label: 'cc', name: 'Ilhas Cocos'},
	{label: 'cd', name: 'República Democrática do Congo'},
	{label: 'cf', name: 'República Centro-Africana'},
	{label: 'cg', name: 'República do Congo'},
	{label: 'ch', name: 'Suíça'},
	{label: 'ci', name: 'Costa do Marfim'},
	{label: 'ck', name: 'Ilhas Cook'},
	{label: 'cl', name: 'Chile'},
	{label: 'cm', name: 'Camarões'},
	{label: 'cn', name: 'República Popular da China'},
	{label: 'co', name: 'Colômbia'},
	{label: 'cr', name: 'Costa Rica'},
	{label: 'cu', name: 'Cuba'},
	{label: 'cv', name: 'Cabo Verde'},
	{label: 'cx', name: 'Ilha Natal'},
	{label: 'cy', name: 'Chipre'},
	{label: 'cz', name: 'República Tcheca'},
	{label: 'de', name: 'Alemanha (Deutschland)'},
	{label: 'dj', name: 'Djibouti'},
	{label: 'dk', name: 'Dinamarca'},
	{label: 'dm', name: 'Dominica'},
	{label: 'do', name: 'República Dominicana'},
	{label: 'dz', name: 'Argélia'},
	{label: 'ec', name: 'Equador'},
	{label: 'ee', name: 'Estónia'},
	{label: 'eg', name: 'Egipto'},
	{label: 'er', name: 'Eritreia'},
	{label: 'es', name: 'Espanha'},
	{label: 'et', name: 'Etiópia'},
	{label: 'eu', name: 'Europa'},
	{label: 'fi', name: 'Finlândia'},
	{label: 'fj', name: 'Fiji'},
	{label: 'fk', name: 'Malvinas (Falkland Islands)'},
	{label: 'fm', name: 'Estados Federados da Micronésia'},
	{label: 'fo', name: 'Ilhas Feroé'},
	{label: 'fr', name: 'França'},
	{label: 'ga', name: 'Gabão'},
	{label: 'uk', name: 'Reino Unido'},
	{label: 'gd', name: 'Granada'},
	{label: 'ge', name: 'Geórgia'},
	{label: 'gf', name: 'Guiana Francesa'},
	{label: 'gg', name: 'Guernsey'},
	{label: 'gh', name: 'Gana'},
	{label: 'gi', name: 'Gibraltar'},
	{label: 'gl', name: 'Gronelândia'},
	{label: 'gm', name: 'Gâmbia'},
	{label: 'gn', name: 'Guiné'},
	{label: 'gp', name: 'Guadalupe'},
	{label: 'gq', name: 'Guiné Equatorial'},
	{label: 'gr', name: 'Grécia'},
	{label: 'gs', name: 'Ilhas Geórgia do Sul e Sandwich do Sul'},
	{label: 'gt', name: 'Guatemala'},
	{label: 'gu', name: 'Guam'},
	{label: 'gw', name: 'Guiné-Bissau'},
	{label: 'gy', name: 'Guiana'},
	{label: 'hk', name: 'Hong Kong'},
	{label: 'hm', name: 'Ilha Heard e Ilhas McDonald'},
	{label: 'hn', name: 'Honduras'},
	{label: 'hr', name: 'Croácia'},
	{label: 'ht', name: 'Haiti'},
	{label: 'hu', name: 'Hungria'},
	{label: 'id', name: 'Indonésia'},
	{label: 'ie', name: 'Irlanda'},
	{label: 'il', name: 'Israel'},
	{label: 'im', name: 'Ilha de Man'},
	{label: 'in', name: 'Índia'},
	{label: 'io', name: 'Território Britânico do Oceano Índico'},
	{label: 'iq', name: 'Iraque'},
	{label: 'ir', name: 'Irão'},
	{label: 'is', name: 'Islândia'},
	{label: 'it', name: 'Itália'},
	{label: 'je', name: 'Jersey'},
	{label: 'jm', name: 'Jamaica'},
	{label: 'jo', name: 'Jordânia'},
	{label: 'jp', name: 'Japão'},
	{label: 'ke', name: 'Quénia'},
	{label: 'kg', name: 'Quirguistão'},
	{label: 'kh', name: 'Camboja'},
	{label: 'ki', name: 'Kiribati'},
	{label: 'km', name: 'Comores'},
	{label: 'kn', name: 'Saint Kitts e Nevis'},
	{label: 'kr', name: 'Coreia do Sul'},
	{label: 'kw', name: 'Kuwait'},
	{label: 'ky', name: 'Ilhas Caiman'},
	{label: 'kz', name: 'Cazaquistão'},
	{label: 'la', name: 'Laos'},
	{label: 'lb', name: 'Líbano'},
	{label: 'lc', name: 'Santa Lúcia'},
	{label: 'li', name: 'Liechtenstein'},
	{label: 'lk', name: 'Sri Lanka'},
	{label: 'lr', name: 'Libéria'},
	{label: 'ls', name: 'Lesoto'},
	{label: 'lt', name: 'Lituânia'},
	{label: 'lu', name: 'Luxemburgo'},
	{label: 'lv', name: 'Letónia'},
	{label: 'ly', name: 'Líbia'},
	{label: 'ma', name: 'Marrocos'},
	{label: 'mc', name: 'Mónaco'},
	{label: 'md', name: 'Moldávia'},
	{label: 'me', name: 'Montenegro'},
	{label: 'mg', name: 'Madagáscar'},
	{label: 'mh', name: 'Ilhas Marshall'},
	{label: 'mk', name: 'Antiga República Jugoslava da Macedónia'},
	{label: 'ml', name: 'Mali'},
	{label: 'mm', name: 'Myanmar'},
	{label: 'mn', name: 'Mongólia'},
	{label: 'mo', name: 'Macau'},
	{label: 'mp', name: 'Marianas Setentrionais'},
	{label: 'mq', name: 'Martinica'},
	{label: 'mr', name: 'Mauritânia'},
	{label: 'ms', name: 'Montserrat'},
	{label: 'mt', name: 'Malta'},
	{label: 'mu', name: 'Maurício'},
	{label: 'mv', name: 'Maldivas'},
	{label: 'mw', name: 'Malawi'},
	{label: 'mx', name: 'México'},
	{label: 'my', name: 'Malásia'},
	{label: 'mz', name: 'Moçambique'},
	{label: 'nb', name: 'Namíbia'},
	{label: 'nc', name: 'Nova Caledónia'},
	{label: 'ne', name: 'Níger'},
	{label: 'nf', name: 'Ilha Norfolk'},
	{label: 'ng', name: 'Nigéria'},
	{label: 'ni', name: 'Nicarágua'},
	{label: 'nl', name: 'Países Baixos'},
	{label: 'no', name: 'Noruega'},
	{label: 'np', name: 'Nepal'},
	{label: 'nr', name: 'Nauru'},
	{label: 'nu', name: 'Niue'},
	{label: 'nz', name: 'Nova Zelândia'},
	{label: 'om', name: 'Omã'},
	{label: 'pa', name: 'Panamá'},
	{label: 'pe', name: 'Peru'},
	{label: 'pf', name: 'Polinésia Francesa'},
	{label: 'pg', name: 'Papua-Nova Guiné'},
	{label: 'ph', name: 'Filipinas'},
	{label: 'pk', name: 'Paquistão'},
	{label: 'pl', name: 'Polónia'},
	{label: 'pm', name: 'Saint-Pierre e Miquelon'},
	{label: 'pn', name: 'Ilhas Pitcairn'},
	{label: 'pr', name: 'Porto Rico'},
	{label: 'ps', name: 'Territórios palestinianos (i.e., Cisjordânia e Faixa de Gaza)'},
	{label: 'pt', name: 'Portugal'},
	{label: 'pw', name: 'Palau'},
	{label: 'py', name: 'Paraguai'},
	{label: 'qa', name: 'Qatar'},
	{label: 're', name: 'Reunião (ilha)'},
	{label: 'ro', name: 'Roménia'},
	{label: 'ru', name: 'Rússia'},
	{label: 'rw', name: 'Ruanda'},
	{label: 'sa', name: 'Arábia Saudita'},
	{label: 'sb', name: 'Ilhas Salomão'},
	{label: 'sc', name: 'Seychelles'},
	{label: 'sd', name: 'Sudão'},
	{label: 'se', name: 'Suécia'},
	{label: 'sg', name: 'Singapura'},
	{label: 'sh', name: 'Santa Helena (território)'},
	{label: 'si', name: 'Eslovénia'},
	{label: 'sj', name: 'Ilhas Svalbard e Jan Mayen'},
	{label: 'sk', name: 'Eslováquia'},
	{label: 'sl', name: 'Serra Leoa'},
	{label: 'sm', name: 'San Marino'},
	{label: 'sn', name: 'Senegal'},
	{label: 'so', name: 'Somália'},
	{label: 'sr', name: 'Suriname'},
	{label: 'ss', name: 'Sudão do Sul'},
	{label: 'st', name: 'São Tomé e Príncipe'},
	{label: 'sv', name: 'El Salvador'},
	{label: 'sy', name: 'Síria'},
	{label: 'sz', name: 'Suazilândia'},
	{label: 'tc', name: 'Ilhas Turcas e Caicos'},
	{label: 'td', name: 'Chade'},
	{label: 'tf', name: 'Terras Austrais e Antárticas Francesas'},
	{label: 'tg', name: 'Togo'},
	{label: 'th', name: 'Tailândia'},
	{label: 'tj', name: 'Tajiquistão'},
	{label: 'tk', name: 'Tokelau'},
	{label: 'tl', name: 'Timor-Leste'},
	{label: 'tm', name: 'Turquemenistão'},
	{label: 'tn', name: 'Tunísia'},
	{label: 'to', name: 'Tonga'},
	{label: 'tr', name: 'Turquia'},
	{label: 'tt', name: 'Trinidad e Tobago'},
	{label: 'tv', name: 'Tuvalu'},
	{label: 'tw', name: 'Taiwan'},
	{label: 'tz', name: 'Tanzânia'},
	{label: 'ua', name: 'Ucrânia'},
	{label: 'ug', name: 'Uganda'},
	{label: 'uk', name: 'Reino Unido'},
	{label: 'um', name: 'Ilhas Menores Distantes dos Estados Unidos'},
	{label: 'us', name: 'selected="selected">Estados Unidos'},
	{label: 'uy', name: 'Uruguai'},
	{label: 'uz', name: 'Uzbequistão'},
	{label: 'va', name: 'Vaticano'},
	{label: 'vc', name: 'São Vicente e Granadinas'},
	{label: 've', name: 'Venezuela'},
	{label: 'vg', name: 'Ilhas Virgens Britânicas'},
	{label: 'vi', name: 'Ilhas Virgens Americanas'},
	{label: 'vn', name: 'Vietname'},
	{label: 'vu', name: 'Vanuatu'},
	{label: 'wf', name: 'Wallis e Futuna'},
	{label: 'ws', name: 'Samoa (antes, Samoa Ocidental)'},
	{label: 'ye', name: 'Iémen'},
	{label: 'yt', name: 'Mayotte'},
	{label: 'yu', name: 'Jugoslávia'},
	{label: 'za', name: 'África do Sul'},
	{label: 'zm', name: 'Zâmbia'},
	{label: 'zw', name: 'Zimbabwe'}
];

var language = [
	{label: 'ar',    name: 'Arabic'},
	{label: 'eu',    name: 'Basque'},
	{label: 'bg',    name: 'Bulgarian'},
	{label: 'bn',    name: 'Bengali'},
	{label: 'ca',    name: 'Catalan'},
	{label: 'cs',    name: 'Czech'},
	{label: 'da',    name: 'Danish'},
	{label: 'de',    name: 'German'},
	{label: 'el',    name: 'Greek'},
	{label: 'en',    name: 'English'},
	{label: 'en-AU', name: 'English (Australian)'},
	{label: 'en-GB', name: 'English (Great Britain)'},
	{label: 'es',    name: 'Spanish'},
	{label: 'eu',    name: 'Basque'},
	{label: 'fa',    name: 'Farsi'},
	{label: 'fi',    name: 'Finnish'},
	{label: 'fil',   name: 'Filipino'},
	{label: 'fr',    name: 'French'},
	{label: 'gl',    name: 'Galician'},
	{label: 'gu',    name: 'Gujarati'},
	{label: 'hi',    name: 'Hindi'},
	{label: 'hr',    name: 'Croatian'},
	{label: 'hu',    name: 'Hungarian'},
	{label: 'id',    name: 'Indonesian'},
	{label: 'it',    name: 'Italian'},
	{label: 'iw',    name: 'Hebrew'},
	{label: 'ja',    name: 'Japanese'},
	{label: 'kn',    name: 'Kannada'},
	{label: 'ko',    name: 'Korean'},
	{label: 'lt',    name: 'Lithuanian'},
	{label: 'lv',    name: 'Latvian'},
	{label: 'ml',    name: 'Malayalam'},
	{label: 'mr',    name: 'Marathi'},
	{label: 'nl',    name: 'Dutch'},
	{label: 'nn',    name: 'Norwegian Nynorsk'},
	{label: 'no',    name: 'Norwegian'},
	{label: 'or',    name: 'Oriya'},
	{label: 'pl',    name: 'Polish'},
	{label: 'pt',    name: 'Portuguese'},
	{label: 'pt-BR', name: 'Portuguese (Brazil)'},
	{label: 'pt-PT', name: 'Portuguese (Portugal)'},
	{label: 'rm',    name: 'Romansch'},
	{label: 'ro',    name: 'Romanian'},
	{label: 'ru',    name: 'Russian'},
	{label: 'sk',    name: 'Slovak'},
	{label: 'sl',    name: 'Slovenian'},
	{label: 'sr',    name: 'Serbian'},
	{label: 'sv',    name: 'Swedish'},
	{label: 'tl',    name: 'Tagalog'},
	{label: 'ta',    name: 'Tamil'},
	{label: 'te',    name: 'Telugu'},
	{label: 'th',    name: 'Thai'},
	{label: 'tr',    name: 'Turkish'},
	{label: 'uk',    name: 'Ukrainian'},
	{label: 'vi',    name: 'Vietnamese'},
	{label: 'zh-CN', name: 'Chinese (Simplified)'},
	{label: 'zh-TW', name: 'Chinese (Traditional)'}
];
